version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  consumer:
    build: .
    depends_on:
      - kafka
